name: CI
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [
          "3.1",
        ]
        gemfile: [
          "gemfiles/mongoid7",
          "gemfiles/mongoid8",
        ]
        experimental: [false]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 8.0

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Ruby Tests
        run: bin/rspec
